Repository etherlabsio/healthcheck, pull requests merged in 2019-05, with the labels that each got.

#22 Fix tests in package checkers
  .circleci/config.yml
  checkers/diskspace_test.go
  checkers/heartbeat_test.go
Labels: size/S

#21 Add go.mod file
  go.mod
Labels: size/XS

#23 Fix CI
  .circleci/config.yml
  .travis.yml
  README.md
Labels: size/M
